#!/usr/bin/env python3

"""
script to generate statistics about AS-sets seen in the global routing table.
initial code generated by MS co-pilot with the following prompt
AS path: 11039 6461 {37006 343} 327708 327707 7 30844 {37006} ?,
AS path: 11039 6079 3356 37282 37030 {37140} I, validation-state: unknown
AS path: 11039 6461 174 37662 327708 327707 7 30844 {2 37006 37485} ?,
AS path: 11039 6461 {858} 23520 14813 14813 14813 14813 14813 {11139} I,
AS path: 11039 6461 1299 23520 14813 14813 14813 14813 14813 {11139} I,


I have a file with several hundred AS paths, one per line.  A sample of lines

AS path: 11039 6461 {37006 343} 327708 327707 7 30844 {37006} ?,
AS path: 11039 6079 3356 37282 37030 {37140} I, validation-state: unknown
AS path: 11039 6461 174 37662 327708 327707 7 30844 {2 37006 37485} ?,
AS path: 11039 6461 {858} 23520 14813 14813 14813 14813 14813 {11139} I,
AS path: 11039 6461 1299 23520 14813 14813 14813 14813 14813 {11139} I,


I need to:
 - Count the number of times as AS-set (denoted by curly braces such as {65222} that are origin ASes (which is when the set is the right most ASN before the orig
in code (which can be "?", "I", or "E"))
 - Count the number of AS-sets that are transit ASes (that is, have "normal", non-set ASNs to the left and right of the set;
 - Count the number of unique sets;
 - Count the number of sets that contain exactly ONE ASN (eg, {65111});
 - Count the number of set that contain more than one ASN (eg {65111 65222})

agallo@foghorn:~/general/MANRS-NetOpsRevWG$ clear
agallo@foghorn:~/general/MANRS-NetOpsRevWG$ cat analyzeASsets.py
#!/usr/bin/env python3

"""
script to generate statistics about AS-sets seen in the global routing table.
initial code generated by MS co-pilot with the following prompt
AS path: 11039 6461 {37006 343} 327708 327707 7 30844 {37006} ?,
AS path: 11039 6079 3356 37282 37030 {37140} I, validation-state: unknown
AS path: 11039 6461 174 37662 327708 327707 7 30844 {2 37006 37485} ?,
AS path: 11039 6461 {858} 23520 14813 14813 14813 14813 14813 {11139} I,
AS path: 11039 6461 1299 23520 14813 14813 14813 14813 14813 {11139} I,


I have a file with several hundred AS paths, one per line.  A sample of lines

AS path: 11039 6461 {37006 343} 327708 327707 7 30844 {37006} ?,
AS path: 11039 6079 3356 37282 37030 {37140} I, validation-state: unknown
AS path: 11039 6461 174 37662 327708 327707 7 30844 {2 37006 37485} ?,
AS path: 11039 6461 {858} 23520 14813 14813 14813 14813 14813 {11139} I,
AS path: 11039 6461 1299 23520 14813 14813 14813 14813 14813 {11139} I,


I need to:
 - Count the number of times as AS-set (denoted by curly braces such as {65222} that are origin ASes (which is when the set is the right most ASN before the origin code (which can be "?", "I", or "E"))
 - Count the number of AS-sets that are transit ASes (that is, have "normal", non-set ASNs to the left and right of the set;
 - Count the number of unique sets;
 - Count the number of sets that contain exactly ONE ASN (eg, {65111});
 - Count the number of set that contain more than one ASN (eg {65111 65222})

write a python script that will read from a file called "AS-sets_28SEP2026.txt" and produce the above statistics
"""

import re
from collections import Counter

INPUT_FILE = "AS-sets_28SEP2026.txt"

# look for AS-sets in the AS path, denoted by curly braces;
# sets can contain one or more ASNs
# Matches AS-sets such as:
# {65111}
# {65111 65222}
SET_RE = re.compile(r"\{([^}]*)\}")


# sets can either be origin or transit
# Matches the origin code at the end of the AS path
# Examples:
# ... {37006} ?,
# ... {11139} I,
# ... 3356 E,
ORIGIN_RE = re.compile(r"\s([?IE])\s*,?\s*(?:validation-state:.*)?$", re.IGNORECASE)


def extract_path(line):
    """Remove leading 'AS path:' and trailing origin code."""
    if not line.startswith("AS path:"):
        return None

    path = line[len("AS path:"):].strip()

    m = ORIGIN_RE.search(path)
    if not m:
        return None

    origin_code = m.group(1)
    path = path[:m.start()].strip()

    return path, origin_code


def tokenize_path(path):
    """
    Split path into ASNs and AS-sets while preserving AS-sets as single tokens.

    Example:
        11039 6461 {37006 343} 327708

    Returns:
        ['11039', '6461', '{37006 343}', '327708']
    """
    return re.findall(r"\{[^}]+\}|\d+", path)


def main():
    total_sets = 0
    origin_sets = 0
    transit_sets = 0

    one_asn_sets = 0
    multi_asn_sets = 0

    unique_sets = Counter()

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            result = extract_path(line)
            if not result:
                continue

            path, origin_code = result
            tokens = tokenize_path(path)

            for idx, token in enumerate(tokens):
                if not (token.startswith("{") and token.endswith("}")):
                    continue

                total_sets += 1

                # Normalize whitespace inside set for uniqueness
                members = token[1:-1].split()
                normalized_set = "{" + " ".join(members) + "}"
                unique_sets[normalized_set] += 1

                if len(members) == 1:
                    one_asn_sets += 1
                else:
                    multi_asn_sets += 1

                # Origin AS-set:
                # right-most token in AS path before origin code
                if idx == len(tokens) - 1:
                    origin_sets += 1

                # Transit AS-set:
                # has a non-set ASN on both sides
                left_is_asn = (
                    idx > 0
                    and not tokens[idx - 1].startswith("{")
                )

                right_is_asn = (
                    idx < len(tokens) - 1
                    and not tokens[idx + 1].startswith("{")
                )

                if left_is_asn and right_is_asn:
                    transit_sets += 1

    print()
    print("AS-SET STATISTICS")
    print("=================")
    print(f"Total AS-set occurrences       : {total_sets}")
    print(f"Origin AS-set occurrences      : {origin_sets}")
    print(f"Transit AS-set occurrences     : {transit_sets}")
    print(f"Unique AS-sets                 : {len(unique_sets)}")
    print(f"Sets with exactly one ASN      : {one_asn_sets}")
    print(f"Sets with more than one ASN    : {multi_asn_sets}")

    print()
    print("TOP 20 MOST COMMON AS-SETS")
    print("==========================")
    for aset, count in unique_sets.most_common(20):
        print(f"{count:6d}  {aset}")


if __name__ == "__main__":
    main()
